Repository threeback/kicketing-back, pull requests merged in 2024-04, with the labels that each got.

#6 Feature/#2 로그인
  build.gradle
  src/main/java/tback/kicketingback/auth/controller/RefreshTokenController.java
  src/main/java/tback/kicketingback/auth/dto/TokenResponse.java
  src/main/java/tback/kicketingback/auth/exception/AuthenticationExceptionHandler.java
  src/main/java/tback/kicketingback/auth/exception/exceptions/ExpiredTokenException.java
  src/main/java/tback/kicketingback/auth/exception/exceptions/InvalidJwtTokenException.java
  src/main/java/tback/kicketingback/auth/exception/exceptions/PayloadEmailMissingException.java
  src/main/java/tback/kicketingback/auth/exception/exceptions/TokenExtractionException.java
  src/main/java/tback/kicketingback/auth/interceptor/UserInterceptor.java
  src/main/java/tback/kicketingback/auth/jwt/JwtLogin.java
  src/main/java/tback/kicketingback/auth/jwt/JwtTokenExtractor.java
  src/main/java/tback/kicketingback/auth/jwt/JwtTokenProvider.java
  src/main/java/tback/kicketingback/auth/jwt/JwtTokenType.java
  src/main/java/tback/kicketingback/global/AbstractExceptionHandler.java
  src/main/java/tback/kicketingback/global/config/InterceptorAuthConfig.java
  src/main/java/tback/kicketingback/global/config/RedisConfig.java
  src/main/java/tback/kicketingback/global/config/UserArgumentResolver.java
  src/main/java/tback/kicketingback/global/repository/RedisRepository.java
  src/main/java/tback/kicketingback/user/domain/User.java
  src/main/java/tback/kicketingback/user/exception/UserExceptionHandler.java
  src/main/java/tback/kicketingback/user/exception/exceptions/AlreadySamePasswordException.java
  src/main/java/tback/kicketingback/user/exception/exceptions/NoSuchUserException.java
  src/main/java/tback/kicketingback/user/repository/UserRepository.java
  src/main/java/tback/kicketingback/user/signin/controller/SignInController.java
  src/main/java/tback/kicketingback/user/signin/dto/SignInRequest.java
  src/main/java/tback/kicketingback/user/signin/service/SignInService.java
  src/test/java/tback/kicketingback/user/domain/UserTest.java
  src/test/java/tback/kicketingback/user/repository/FakeUserRepository.java
  src/test/java/tback/kicketingback/user/signin/userSignInTest.java
Labels: 💫 feat

#9 Feature/#8 레디스 설정 변경
  src/main/java/tback/kicketingback/KicketingBackApplication.java
  src/main/java/tback/kicketingback/auth/controller/RefreshTokenController.java
  src/main/java/tback/kicketingback/global/config/RedisConfig.java
  src/main/java/tback/kicketingback/global/repository/RedisRepository.java
  src/main/java/tback/kicketingback/user/signin/service/SignInService.java
  src/main/resources/redis-server.yml
  src/test/java/tback/kicketingback/user/signin/UserSignInTest.java
Labels: ⚙️ chore, 🗃 infra

#10 Feature/#3 회원가입
  build.gradle
  src/main/java/tback/kicketingback/email/service/EmailAuthService.java
  src/main/java/tback/kicketingback/global/config/AsyncConfiguration.java
  src/main/java/tback/kicketingback/global/config/InterceptorAuthConfig.java
  src/main/java/tback/kicketingback/global/encode/PasswordEncoderSHA256.java
  src/main/java/tback/kicketingback/user/domain/User.java
  src/main/java/tback/kicketingback/user/exception/UserExceptionHandler.java
  src/main/java/tback/kicketingback/user/exception/exceptions/AlreadyEmailAuthCompleteException.java
  src/main/java/tback/kicketingback/user/exception/exceptions/AuthInvalidNameException.java
  src/main/java/tback/kicketingback/user/exception/exceptions/EmailAuthIncompleteException.java
  src/main/java/tback/kicketingback/user/exception/exceptions/EmailCreateException.java
  src/main/java/tback/kicketingback/user/exception/exceptions/EmailDuplicatedException.java
  src/main/java/tback/kicketingback/user/exception/exceptions/EmailSendException.java
  src/main/java/tback/kicketingback/user/exception/exceptions/MismatchEmailAuthCodeException.java
  src/main/java/tback/kicketingback/user/exception/exceptions/PasswordEncodeException.java
  src/main/java/tback/kicketingback/user/repository/UserRepository.java
  src/main/java/tback/kicketingback/user/signup/controller/SignUpController.java
  src/main/java/tback/kicketingback/user/signup/dto/request/EmailCodeRequest.java
  src/main/java/tback/kicketingback/user/signup/dto/request/EmailConfirmRequest.java
  src/main/java/tback/kicketingback/user/signup/dto/request/SignUpRequest.java
  src/main/java/tback/kicketingback/user/signup/mail/HtmlEmailTemplate.java
  src/main/java/tback/kicketingback/user/signup/mail/Mail.java
  src/main/java/tback/kicketingback/user/signup/mail/SmtpMailSender.java
  src/main/java/tback/kicketingback/user/signup/mail/SmtpService.java
  src/main/java/tback/kicketingback/user/signup/service/DefaultSignUpService.java
  src/main/java/tback/kicketingback/user/signup/service/SignUpEmailService.java
  src/main/java/tback/kicketingback/user/signup/service/SignUpService.java
  src/main/java/tback/kicketingback/user/signup/utils/NumberUtil.java
  src/test/java/tback/kicketingback/global/encode/PasswordEncoderSHA256Test.java
  src/test/java/tback/kicketingback/user/domain/UserTest.java
  src/test/java/tback/kicketingback/user/repository/FakeUserRepository.java
  src/test/java/tback/kicketingback/user/signup/SignupTest.java
  src/test/java/tback/kicketingback/user/signup/UserSignUpEmailAuthTest.java
  src/test/java/tback/kicketingback/user/signup/mail/SmtpServiceTest.java
  src/test/java/tback/kicketingback/user/util/NumberUtilTest.java
Labels: 💫 feat

#12 chore : cors, interceptor 인가 설정
  src/main/java/tback/kicketingback/auth/interceptor/UserInterceptor.java
  src/main/java/tback/kicketingback/global/config/CORSConfig.java
Labels: ⚙️ chore

#14 Hotfix/#13 회원가입 이메일인증
  src/main/java/tback/kicketingback/KicketingBackApplication.java
  src/main/java/tback/kicketingback/email/service/EmailAuthService.java
  src/main/java/tback/kicketingback/global/config/InterceptorAuthConfig.java
  src/main/java/tback/kicketingback/global/dto/BaseTimeEntity.java
  src/main/java/tback/kicketingback/user/domain/User.java
  src/main/java/tback/kicketingback/user/signup/controller/SignUpController.java
  src/main/java/tback/kicketingback/user/signup/dto/request/SignUpRequest.java
  src/main/java/tback/kicketingback/user/signup/service/DefaultSignUpService.java
  src/main/java/tback/kicketingback/user/signup/service/SignUpEmailService.java
Labels: 🐛 bug

#16 Refactor/#15 토큰위치 재배치
  src/main/java/tback/kicketingback/auth/controller/RefreshTokenController.java
  src/main/java/tback/kicketingback/auth/jwt/JwtTokenExtractor.java
  src/main/java/tback/kicketingback/global/config/UserArgumentResolver.java
  src/main/java/tback/kicketingback/user/signin/controller/SignInController.java
Labels: ♻️ refactor

#23 feat : API 요청시 Valid 검증 추가
  build.gradle
  src/main/java/tback/kicketingback/auth/controller/RefreshTokenController.java
  src/main/java/tback/kicketingback/auth/exception/AuthenticationExceptionHandler.java
  src/main/java/tback/kicketingback/auth/oauth/exception/OauthExceptionHandler.java
  src/main/java/tback/kicketingback/auth/oauth/service/OauthSignupService.java
  src/main/java/tback/kicketingback/global/exception/AbstractExceptionHandler.java
  src/main/java/tback/kicketingback/global/exception/GlobalExceptionHandler.java
  src/main/java/tback/kicketingback/user/domain/User.java
  src/main/java/tback/kicketingback/user/exception/UserExceptionHandler.java
  src/main/java/tback/kicketingback/user/signin/controller/SignInController.java
  src/main/java/tback/kicketingback/user/signin/dto/SignInRequest.java
  src/main/java/tback/kicketingback/user/signin/service/SignInService.java
  src/main/java/tback/kicketingback/user/signup/controller/SignUpController.java
  src/main/java/tback/kicketingback/user/signup/dto/request/EmailCodeRequest.java
  src/main/java/tback/kicketingback/user/signup/dto/request/EmailConfirmRequest.java
  src/main/java/tback/kicketingback/user/signup/dto/request/SignUpRequest.java
  src/main/java/tback/kicketingback/user/signup/service/DefaultSignUpService.java
  src/test/java/tback/kicketingback/user/signin/UserSignInTest.java
Labels: 💫 feat

#25 fix : EmailAuthIncompleteException 핸들러의 파라미터 타입 수정
  src/main/java/tback/kicketingback/user/exception/UserExceptionHandler.java
Labels: 🐛 bug

#27 refact : 로그인 코드 리팩토링
  src/main/java/tback/kicketingback/auth/dto/TokenResponse.java
  src/main/java/tback/kicketingback/auth/oauth/controller/OauthSignInController.java
  src/main/java/tback/kicketingback/user/signin/controller/SignInController.java
Labels: ♻️ refactor

#29 fix : 오어스 회원가입 이메일 전송 버그 수정
  src/main/java/tback/kicketingback/auth/oauth/service/OauthSignupService.java
Labels: 🐛 bug

#32 refact : 예외 메세지 형식 통일
  src/main/java/tback/kicketingback/auth/exception/exceptions/ExpiredTokenException.java
  src/main/java/tback/kicketingback/auth/exception/exceptions/PayloadEmailMissingException.java
  src/main/java/tback/kicketingback/auth/exception/exceptions/TokenExtractionException.java
  src/main/java/tback/kicketingback/user/exception/exceptions/AlreadyEmailAuthCompleteException.java
  src/main/java/tback/kicketingback/user/exception/exceptions/AlreadySamePasswordException.java
  src/main/java/tback/kicketingback/user/exception/exceptions/AuthInvalidEmailException.java
  src/main/java/tback/kicketingback/user/exception/exceptions/AuthInvalidNameException.java
  src/main/java/tback/kicketingback/user/exception/exceptions/AuthInvalidPasswordException.java
  src/main/java/tback/kicketingback/user/exception/exceptions/EmailAuthIncompleteException.java
  src/main/java/tback/kicketingback/user/exception/exceptions/EmailCreateException.java
  src/main/java/tback/kicketingback/user/exception/exceptions/EmailDuplicatedException.java
  src/main/java/tback/kicketingback/user/exception/exceptions/EmailFormatException.java
  src/main/java/tback/kicketingback/user/exception/exceptions/EmailSendException.java
  src/main/java/tback/kicketingback/user/exception/exceptions/MismatchEmailAuthCodeException.java
  src/main/java/tback/kicketingback/user/exception/exceptions/NoSuchUserException.java
  src/main/java/tback/kicketingback/user/exception/exceptions/PasswordEncodeException.java
  src/main/java/tback/kicketingback/user/exception/exceptions/UserPasswordEmptyException.java
Labels: ♻️ refactor
