Repository threeback/kicketing-back, pull requests merged in 2024-05, with the labels that each got.

#38 feat : 공연 예매 도메인 엔티티 작성
  src/main/java/tback/kicketingback/performance/domain/Performance.java
  src/main/java/tback/kicketingback/performance/domain/Place.java
  src/main/java/tback/kicketingback/performance/domain/Reservation.java
  src/main/java/tback/kicketingback/performance/domain/Seat.java
Labels: 💫 feat

#39 Revert "feat : 공연 예매 도메인 엔티티 작성"
  src/main/java/tback/kicketingback/performance/domain/Performance.java
  src/main/java/tback/kicketingback/performance/domain/Place.java
  src/main/java/tback/kicketingback/performance/domain/Reservation.java
  src/main/java/tback/kicketingback/performance/domain/Seat.java
Labels: 💫 feat

#40 feat : 공연 예매 도메인 엔티티 작성
  src/main/java/tback/kicketingback/performance/domain/Performance.java
  src/main/java/tback/kicketingback/performance/domain/Place.java
  src/main/java/tback/kicketingback/performance/domain/Reservation.java
  src/main/java/tback/kicketingback/performance/domain/Seat.java
Labels: 💫 feat

#43 Refactor/#42 auth
  src/main/java/tback/kicketingback/auth/controller/RefreshTokenController.java
  src/main/java/tback/kicketingback/auth/interceptor/UserInterceptor.java
  src/main/java/tback/kicketingback/auth/jwt/JwtTokenExtractor.java
  src/main/java/tback/kicketingback/auth/jwt/JwtTokenProvider.java
  src/main/java/tback/kicketingback/auth/service/RefreshTokenService.java
Labels: ♻️ refactor

#45 feat : 로그아웃 기능
  src/main/java/tback/kicketingback/auth/dto/TokenResponse.java
  src/main/java/tback/kicketingback/user/signout/controller/SignOutController.java
  src/main/java/tback/kicketingback/user/signout/service/SignOutService.java
Labels: 💫 feat

#48 Feature/#47 cicd
  .github/workflows/gradle.yml
  build.gradle
Labels: 🗃 infra

#49 Feature/#47 cicd
  .github/workflows/gradle.yml
  build.gradle
Labels: 🗃 infra

#46 Feature/#35 회원정보
  src/main/java/tback/kicketingback/auth/oauth/service/OauthSignupService.java
  src/main/java/tback/kicketingback/user/controller/UserController.java
  src/main/java/tback/kicketingback/user/domain/User.java
  src/main/java/tback/kicketingback/user/domain/UserState.java
  src/main/java/tback/kicketingback/user/dto/request/AddressRequest.java
  src/main/java/tback/kicketingback/user/dto/request/InformRequest.java
  src/main/java/tback/kicketingback/user/dto/request/NameRequest.java
  src/main/java/tback/kicketingback/user/dto/request/PasswordRequest.java
  src/main/java/tback/kicketingback/user/exception/UserExceptionHandler.java
  src/main/java/tback/kicketingback/user/exception/exceptions/AuthInvalidStateException.java
  src/main/java/tback/kicketingback/user/service/UserService.java
  src/main/java/tback/kicketingback/user/signup/mail/HtmlEmailTemplate.java
  src/main/java/tback/kicketingback/user/signup/service/DefaultSignUpService.java
  src/test/java/tback/kicketingback/user/domain/UserTest.java
  src/test/java/tback/kicketingback/user/signin/UserSignInTest.java
  src/test/java/tback/kicketingback/user/signup/SignupTest.java
Labels: 💫 feat

#53 fix : 이미 가입된 이메일에 인증 번호 보내는 버그 수정
  src/main/java/tback/kicketingback/global/exception/AbstractExceptionHandler.java
  src/main/java/tback/kicketingback/user/exception/UserExceptionHandler.java
  src/main/java/tback/kicketingback/user/service/UserService.java
  src/main/java/tback/kicketingback/user/signup/controller/SignUpController.java
Labels: 🐛 bug

#54 chore : QueryDsl 종속성 설정
  build.gradle
Labels: ⚙️ chore

#57 fix : 배포시 plain 파일 생성 하지 않도록 수정
  build.gradle
Labels: 🐛 bug

#55 refact : 기능 요구사항 변경에 따른 수정
  src/main/java/tback/kicketingback/performance/domain/Reservation.java
Labels: ♻️ refactor

#60 Refactor/#59 좌석등급 엔티티 수정
  src/main/java/tback/kicketingback/performance/domain/OnStage.java
  src/main/java/tback/kicketingback/performance/domain/SeatGrade.java
Labels: ♻️ refactor

#61 Feature/#41 공연정보 제공
  src/main/java/tback/kicketingback/global/config/InterceptorAuthConfig.java
  src/main/java/tback/kicketingback/global/exception/GlobalExceptionHandler.java
  src/main/java/tback/kicketingback/performance/controller/PerformanceController.java
  src/main/java/tback/kicketingback/performance/domain/Place.java
  src/main/java/tback/kicketingback/performance/domain/SeatGrade.java
  src/main/java/tback/kicketingback/performance/domain/Star.java
  src/main/java/tback/kicketingback/performance/dto/DateUnit.java
  src/main/java/tback/kicketingback/performance/dto/DetailPerformanceDTO.java
  src/main/java/tback/kicketingback/performance/dto/GetPerformancesRequest.java
  src/main/java/tback/kicketingback/performance/dto/GetPerformancesResponse.java
  src/main/java/tback/kicketingback/performance/dto/GetPerformancesSize.java
  src/main/java/tback/kicketingback/performance/dto/PerformanceDTO.java
  src/main/java/tback/kicketingback/performance/dto/PerformancePlaceDTO.java
  src/main/java/tback/kicketingback/performance/dto/PlaceDTO.java
  src/main/java/tback/kicketingback/performance/dto/Range.java
  src/main/java/tback/kicketingback/performance/dto/SeatGradeDTO.java
  src/main/java/tback/kicketingback/performance/dto/SimplePerformanceDTO.java
  src/main/java/tback/kicketingback/performance/dto/SimplePerformancePlaceDTO.java
  src/main/java/tback/kicketingback/performance/dto/StarDTO.java
  src/main/java/tback/kicketingback/performance/exception/PerformanceExceptionHandler.java
  src/main/java/tback/kicketingback/performance/exception/exceptions/InvalidGetPerformanceDateUnitException.java
  src/main/java/tback/kicketingback/performance/exception/exceptions/InvalidGetPerformanceSizeException.java
  src/main/java/tback/kicketingback/performance/repository/PerformanceRepository.java
  src/main/java/tback/kicketingback/performance/repository/SeatGradeRepository.java
  src/main/java/tback/kicketingback/performance/service/PerformanceService.java
  src/test/java/tback/kicketingback/performance/domain/type/GenreTest.java
  src/test/java/tback/kicketingback/performance/dto/DateUnitTest.java
  src/test/java/tback/kicketingback/performance/dto/GetPerformancesSizeTest.java
  src/test/java/tback/kicketingback/performance/repository/PerformanceRepositoryTest.java
  src/test/java/tback/kicketingback/performance/service/PerformanceServiceTest.java
  src/test/java/tback/kicketingback/user/signup/UserSignUpEmailAuthTest.java
Labels: 💫 feat

#64 fix : 존재하지 않는 공연 uuid 예외처리
  src/main/java/tback/kicketingback/performance/exception/PerformanceExceptionHandler.java
  src/main/java/tback/kicketingback/performance/exception/exceptions/InvalidPerformanceUUIDException.java
  src/main/java/tback/kicketingback/performance/repository/PerformanceRepository.java
  src/main/java/tback/kicketingback/performance/service/PerformanceService.java
Labels: 🐛 bug

#68 QueryDSL 리포지토리 클래스명 변경
  src/main/java/tback/kicketingback/performance/repository/PerformanceRepositoryCustom.java
  src/main/java/tback/kicketingback/performance/service/PerformanceService.java
  src/test/java/tback/kicketingback/performance/repository/PerformanceRepositoryCustomTest.java
Labels: ♻️ refactor

#73 Feature/#66 좌석정보 제공
  src/main/java/tback/kicketingback/global/exception/AbstractExceptionHandler.java
  src/main/java/tback/kicketingback/performance/controller/ReservationController.java
  src/main/java/tback/kicketingback/performance/domain/Reservation.java
  src/main/java/tback/kicketingback/performance/domain/Seat.java
  src/main/java/tback/kicketingback/performance/dto/AlreadySelectedSeatResponse.java
  src/main/java/tback/kicketingback/performance/dto/GetSeatInfoResponse.java
  src/main/java/tback/kicketingback/performance/dto/LockOnStageSeatsRequest.java
  src/main/java/tback/kicketingback/performance/dto/SeatReservationDTO.java
  src/main/java/tback/kicketingback/performance/dto/SeatRowCol.java
  src/main/java/tback/kicketingback/performance/dto/SimpleSeatDTO.java
  src/main/java/tback/kicketingback/performance/exception/PerformanceExceptionHandler.java
  src/main/java/tback/kicketingback/performance/exception/exceptions/AlreadySelectedSeatException.java
  src/main/java/tback/kicketingback/performance/exception/exceptions/DuplicateSeatSelectionException.java
  src/main/java/tback/kicketingback/performance/exception/exceptions/InvalidPerformanceException.java
  src/main/java/tback/kicketingback/performance/exception/exceptions/InvalidSeatIdException.java
  src/main/java/tback/kicketingback/performance/exception/exceptions/NoAvailableSeatsException.java
  src/main/java/tback/kicketingback/performance/repository/PerformanceRepositoryCustom.java
  src/main/java/tback/kicketingback/performance/repository/ReservationRepositoryCustom.java
  src/main/java/tback/kicketingback/performance/service/ReservationService.java
  src/main/resources/application.yml
  src/test/java/tback/kicketingback/performance/service/ReservationServiceTest.java
Labels: 💫 feat

#78 refact : SeatGradeDTO 수정
  src/main/java/tback/kicketingback/performance/dto/SeatGradeDTO.java
  src/main/java/tback/kicketingback/performance/service/PerformanceService.java
  src/main/java/tback/kicketingback/performance/service/ReservationService.java
Labels: ♻️ refactor

#81 fix : 유저 본인이 선택한 좌석은 다른 유저의 점유 좌석 체크에서 제외됨
  src/main/java/tback/kicketingback/performance/service/ReservationService.java
Labels: 🐛 bug

#87 fix : classpath 설정이 빠져있던 버그 수정
  src/main/resources/application.yml
Labels: 🐛 bug

#88 refact : 예약현황 중복되는 정보 제거하는 리팩토링
  src/main/java/tback/kicketingback/performance/dto/MyReservationsResponse.java
  src/main/java/tback/kicketingback/performance/dto/SimpleReservationDTO.java
  src/main/java/tback/kicketingback/performance/repository/ReservationRepositoryCustom.java
  src/main/java/tback/kicketingback/user/dto/response/MyReservationsInfoResponse.java
  src/main/java/tback/kicketingback/user/service/UserService.java
Labels: ♻️ refactor

#91 fix : 한 유저가 같은 자리를 계속 점유하는 버그 수정
  src/main/java/tback/kicketingback/performance/service/ReservationService.java
Labels: 🐛 bug

#92 feat : 예매취소 엔티티 추가
  src/main/java/tback/kicketingback/performance/domain/CanceledReservation.java
Labels: 💫 feat

#98 fix : 자리 선택 검증 버그 수정
  src/main/java/tback/kicketingback/performance/controller/ReservationController.java
  src/main/java/tback/kicketingback/performance/dto/SelectSeatsRequest.java
Labels: 🐛 bug

#100 Hotfix/#94 결제검증
  src/main/java/tback/kicketingback/performance/domain/type/DiscountType.java
  src/main/java/tback/kicketingback/performance/dto/CompleteReservationRequest.java
  src/main/java/tback/kicketingback/performance/dto/PaymentCancelRequest.java
  src/main/java/tback/kicketingback/performance/dto/PaymentVerifyRequest.java
  src/main/java/tback/kicketingback/performance/repository/ReservationRepositoryCustom.java
  src/main/java/tback/kicketingback/performance/repository/SeatGradeRepository.java
  src/main/java/tback/kicketingback/performance/repository/SeatRepository.java
  src/main/java/tback/kicketingback/performance/service/PaymentService.java
  src/main/java/tback/kicketingback/performance/service/ReservationService.java
  src/main/java/tback/kicketingback/user/controller/UserController.java
  src/test/java/tback/kicketingback/performance/domain/type/DiscountTypeTest.java
Labels: 🐛 bug

#102 feat : 나의 취소 목록 기능 추가
  src/main/java/tback/kicketingback/performance/domain/CanceledReservation.java
  src/main/java/tback/kicketingback/performance/dto/MyCanceledReservationResponse.java
  src/main/java/tback/kicketingback/performance/exception/PerformanceExceptionHandler.java
  src/main/java/tback/kicketingback/performance/repository/CanceledReservationRepository.java
  src/main/java/tback/kicketingback/performance/service/ReservationService.java
  src/main/java/tback/kicketingback/user/controller/UserController.java
  src/main/java/tback/kicketingback/user/dto/response/CanceledReservationDTO.java
  src/main/java/tback/kicketingback/user/service/UserService.java
Labels: 💫 feat

#104 Hotfix/#103 공연 버그
  src/main/java/tback/kicketingback/performance/exception/PerformanceExceptionHandler.java
  src/main/java/tback/kicketingback/performance/service/ReservationService.java
Labels: 🐛 bug

#107 endDate가 지난 공연이 검색되는 버그
  src/main/java/tback/kicketingback/performance/repository/SearchRepository.java
Labels: 🐛 bug

#109 검색 API 기능 추가
  src/main/java/tback/kicketingback/performance/controller/SearchController.java
  src/main/java/tback/kicketingback/performance/domain/PerformanceAutoComplete.java
  src/main/java/tback/kicketingback/performance/dto/PerformanceAutoCompleteResponse.java
  src/main/java/tback/kicketingback/performance/dto/PerformanceSearchRequest.java
  src/main/java/tback/kicketingback/performance/dto/PerformanceSearchResponse.java
  src/main/java/tback/kicketingback/performance/repository/PerformanceAutoCompleteRepository.java
  src/main/java/tback/kicketingback/performance/repository/SearchRepository.java
  src/main/java/tback/kicketingback/performance/service/SearchService.java
Labels: 💫 feat
